#+TITLE: Texts

* Building Careers, Encountering Class Text

** Introduction

Well-paying jobs were the basic motivation for the post-1965 Indian immigration.
At first largely from middle-class, well-educated backgrounds, Indians migrated to the United States to further improve their standard of living.
The contrasting economic conditions in India and the United States in the 1960s and 1970s fed those expectations, and the professional careers and business achievements of Indian immigrants during these decades underlay the "successful immigrant" image attached to the entire group.
This "model minority" myth became entrenched as well among these immigrant themselves, affecting their self-perceptions and their definition of community needs and issues.
By the 1980s, however, the occupational diversity of Indians here was increasing rapidly, and in the 1990s the population included growing numbers of lower-middle- and working-class immigrants, a change most evident in New York City.

Class differences have been important throughout the history of Indian immigration to the United States, and they affect Indian ideas about race, ethnicity, gender, culture, and Americanization.
Indian immigrants in the United States have been studied primarily as a professional population or for their distinctive cultural characteristics; their changing socioeconomic profile has received less attention.
Moreover, the studies of economic success do not sufficiently emphasize the impact of class on ideology or pan-Indian activities; with a few exceptions, the formation of class divisions among Indians and the creation of an increasingly stratified immigrant community have received no sustained examination.
Focusing on economic activities among Indian immigrants in New York City from the 1960s through the 1990s, this chapter outlines the transformation of a predominantly professional population into one encompassing various middle- and working-class occupations.
By the 1990s, whereas some Indians' financial successes made American headlines, other immigrants were unemployed, and many others experienced downward mobility.

** Skilled Migrants

Through the 1950s and 1960s, Indian universities churned out thousands of graduates who faced serious unemployment or underemployment.
The nascent economy of independent India acutely needed trained people, but either sufficient paid employment was not available, or it was available only in areas without urban standards of living.
By 1970, 80 percent of India's doctors resided in urban areas, although these contained less than 20 percent of India's population; and at the same time, 15,000 to 20,000 doctors were without jobs.
Beyond the lack of employment, inadequate work facilities and limited career advancement also confronted Indian professionals.
These employment conditions dissuaded educated and skilled Indians from staying in India, and many turned to overseas migration.
In a single month in 1965, nearly 2,000 Indian doctors took examinations offered by the Educational Council for Foreign Medical Graduates to certify them to work in U.S. hospitals.
Although the movement of Indian professionals to America had already begun in the 1950s, the larger portion of that decade's flow was to Great Britain.
By the early 1970s, with rising British antagonism toward immigrants, it was redirected to the United States, where the 1965 Immigration and Nationality Act had opened the door more widely to immigrants from beyond Europe.

With the USSR's launching of Sputnik in 1957, expenditure for research and development in the United States increased from $7 billion that year to $14 billion by 1966, and the number of scientists and engineers employed in American industry grew correspondingly.
Many of them came from other countries, including India.
The stream of professional immigration from Asian countries, including India, increased along with the growth of Great Society social welfare programs in the United States under President Lyndon Johnson.
In 1965 two new government health programs, Medicare for aged and disabled workers, and Medicaid for low-income persons, were passed, and demand for medical personnel rose throughout the United States.
America produced only 7,000 physicians in 1963---too few to staff the country's expanding health care system.
In 1968 the president of the American Medical Association (AMA) called the nation's health the "best ever," but lamented, "The nation needs more physicians, nurses, and technicians and technologists to meet increasing demands for health care".
The world distribution of medical and scientific professionals, and their training, became issues in international politics.
India worried over losing its best personnel and protested against a "brain drain," as one Indian report in 1965 characterized the exodus of 20,000 physicians and scientists to Western nations.
The AMA countered protests from sending countries by asserting that the United States did not "recruit" foreign medical graduates (FMGs), and challenged the accuracy of figures on Indian doctors in the United States.
But at the same time, the AMA report that in 1964 alone some 8,804 medical interns and residents had arrived in the United States from overseas and that 60 percent of house staff physicians in New York City hospitals had received their medical degrees abroad.

Employment prospects for skilled immigrants in the United States were so inviting that medical doctors even migrated from Britain, and during the 1960s that country also became anxious about physicians leaving for the United States.
But losses of personnel and the resources invested in their education were more serious for developing countries.
Before 1965, 50 percent of all FMGs in the United States came from Europe and the Americas, and only 10 percent from Asia; by 1972, 70 percent came from Asia, with India, the Phiippines, and Korea the leading sources of new arrivals.

Thousands of Indian doctors also came to the United States for advanced medical training every year.
Few returned to India, despite pleading by the Indian government.
The situation was so serious that in the late 1960s the Association for Service to Indian Scholars, or ASSIST, was formed to persuade Indian professionals to return home.
In its first year it received only sixty applications and placed only nineteen people in jobs.
This brain drain was further highlighted by a study from one of India's leading medical institutions, the Medical College of Baroda, in Gujarat.
Of 624 graduates from 1949 to 1965, 194 went abroad for further training, and only 28 returned to India; from 1966 to 1972, of 722 graduates, 390 went abroad, and only one returned.

As a result of this skilled labor emigration, a preponderance of professionals characterized the Indian immigrant population in the United States.
From 1961 to 1968, 67 percent of Indians employed in the United States were in professional categories, and from 1969 to 1971 the figure jumped to 89 percent.
Ninety-three percent of Indians admitted in 1975 were "professional/technical workers" and their spouses and children.
And in 1976 the /New York Times/ reported: "At the end of last year, 1,143 Indians held faculty positions in American colleges and universities".

Although the proportion of highly educated professionals was also large among many other Asian immigrant groups, it was highest among Indians.
In the 1980 U.S. Census, 24.9 percent of Koreans, 25.1 percent of Filipinos, 28.5 percent of Japanese, 32.6 percent of Chinese, and 48.5 percent of Asian Indians were in the "managerial, professional" category.
If we add the "technical, sales, and administrative support" category, 76.percent of employed Asian Indians were contained in these two occupational groupings (the corresponding figures were 52.3 percent of Koreans, 58.4 percent of Filipinos, and 62.7 percent of both Japanese and Chinese).

Although Filipinos had a larger absolute number of medical professionals in the United States than did Indians, the proportion of this group and its influence on immigrant community affairs and politics was greater among Indians.
Moreover, in this category Indians had a larger percentage of doctors than did Filipinos, among whom nurses predominated.
These middle-class Indian immigrants also played a role in perpetuating the model minority image.
When Asian Indians were shown in the 1980 census to have the highest "median income of persons 15 years or older with income" of any ethnic group, including white Americans, the news was celebrated in New York's Indian immigrant circles.
This celebration continued into the 1980s and 1990s, when Indians mentioned the "high income levels" of their group as its leading characteristic.
Similar pronouncements portrayed Indians as new kinds of immigrants, highly educated and sophisticated, who could quite easily integrate into upper- and middle-class America.

While some analysts of Indian migration emphasized U.S. demand and South Asian supply factors in creating this profile, popular writer Joel Kotkin ventured a cultural and religious explanation for Indian immigrant success.
Kotkin stamped Indians as one of the "most recent to emerge of the modern global tribes," and identified certain Indian communities as "tribes within tribes," concluding that "virtually wherever they have settled, they rank among the most professionally and economically mobile groups".
Similar ideas remained prevalent among some Indian immigrants themselves.
The cover letter addressed to two thousand "Businessmen and Professionals" for a 1995 international survey conducted by one Indian community leader in New York stated:

#+begin_quote
This research is based on the premise that culture does influence economics.
The World Bank report makes the assumption that all men are equal and that people all over the world are the same.
As a matter of fact they are not.
This is very well supported by the regional economic landscape of India.
Some regional communities produce better businessmen, some warriors, some /babus/ [white-collar workers], and some others literary giants....
The purpose of this research is to identify Indian socio-economic acumen which [has] made Indians economically enviable.
This research will also help in identifying the most successful community, as perceived by many.
Please send your "Success Story."
Success stories will be analyzed to identify significant characteristics contributing to economic success.
#+end_quote

Not celebrated in 1980 was the U.S. Census documentation that incomes were declining among Indian immigrants who had arrived after 1975.
This changing economic profile, which continued in later decades, was produced not only by the family reunification process but also by shifts in the American economy.
In New York City, where the impact of economic change registered most deeply on the Indian immigrant population, difficult economic conditions followed the city's 1975 fiscal crisis and 1987 stock market crash, including a growing disparity between suburban and city employment conditions and job downsizing.
Roger Sanjek argues that with shrinkage in midlevel jobs in the 1980s, a growing number of immigrants moved into the underground economy of cash transactions, tax avoidance, and subminimum wages.
Global economic changes since the late 1980s, particularly the upsurge of Asian economies, moreover, have created shifts in Asian immigration flows to the United States.
In the 1990s a few young Indian professionals in the United States even began to relocate to India.

** Oral Histories of Early Migrants

In their narratives, Indians who had arrived in the 1960s and early 1970s described decisions to migrate as based on educational and career opportunities.
In some cases this motive was coupled with a desire to break away from family control and to build lives of their own.
At first these immigrants paid little conscious attention to the continuation of Indian values and cultural traditions in the new land.
Most immigrants were men, either single or newly married, some with young families.
In general they were imbued with a "spirit of adventure" and with desire for "making new beginnings," as several put it.

These immigrants found that professional jobs were abundant, and had little difficulty in finding them.
One man explained that on his first day in New York in 1969 he visited several offices with his portfolio of educational degrees and certificates.
"It was a day of my life that I will never forget.
On the very first day---within one day---I had three job offers.
In the evening, I returned to my friend's house, with whom I was rooming in Queens, for his advice on which one to select."

Many Indian medical professionals started as residents and interns in New York's inner-city hospitals.
They saw the chances of establishing successful professional careers as much brighter in the United States than in India.
Many also pursued special courses to advance their skills.
At this early stage they were not concerned about unequal wages or glass ceilings, as many would be in later years.
New York City, with a large number of job opportunities in universities, hospitals, and business firms, soon became a fast-growing point of concentration among Indian immigrants.

Mr. Rao left India in 1968 and worked as an engineer in London for two years.
He had married before leaving India, and his wife and a daughter remained there waiting to join him overseas when he decided to start a new job in New York in 1970.
In view of political and economic conditions in Britain, he felt that the United States would be a better place for both his career and his young family.
During his first year in New York he lived with a friend in a Flushing apartment, and when his wife and daughter joined him in 1971 they moved into an apartment in the building next door.
He continued in the same engineering job for years, receiving promotions and feeling settled in this country.
In 1976, with just a few years' savings, he and his family moved to their own single-family house in Bayside, Queens.
As his daughter grew up, his wife, who also had a college degree, worked in an office.
With a two-earner income, Rao invested successfully in real estate and small businesses.
The Raos were active in their regional Indian organization, which they helped found in Queens in the early 1970s.
They worshipped at a Hindu temple and maintained their traditional food and dress habits at home.

Rao was ready to retire in the late 1990s.
He said he had had a long and good career, but in the last few years he felt as if he had begun to stagnate.
Now, after working hard for all these years, he was ready to return to India.
He was only waiting for his daughter to marry, leaving his wife and himself free from their family responsibilities.
He and his wife had given much freedom to their daughter and would accept her choice of a husband as long as "it is within our basic cultural limits."
His innermost wish was that she would marry an Indian professional so that the young couple could have a stable life, both economically and culturally.

Dr. Chandran came to the United States in 1966 soon after graduating from a medical college in India.
For a few years he worked in a hospital in Ohio, during which time he returned to India to marry a bride from his region and caste.
In 1969, accepting a job offer from a prominent hospital, he and his wife moved to New York.
"In comparison to other places, New York had so many more Indian immigrants.
In Queens, in particular, where we started living, we had many Indian families and friends of our age.
It was like finding a community in which every one was enthusiastic about building cultural and social institutions."
While Dr. Chandran built his medical practice, his wife devoted herself to raising their two sons "in as much a traditional Indian way as possible."
She never worked outside the home, but remained active in Indian community affairs.
"We are grateful to God that my husband's income was more than sufficient for our family, and so I did not have to work."
In the 1980s and 1990s the Chandrans were known as community leaders who made regular financial contributions to religious and cultural activities.

The American economy, which had previously offered Indian immigrants easy entry into American professions, began to change in the early 1970s.
By the mid-1970s U.S. interest groups were protesting against the competition presented by foreign-born professionals, particularly medical doctors.
With the demand for foreign skilled labor declining, in 1976 Congress severely curtailed opportunities for foreign-trained medical graduates to enter the United States with occupational visas.
As a result, immigration of Indian physicians in the 1980s and 1990s occurred primarily through family reunification visas.

Exacerbating the effects of this policy in New York was the city's 1975 fiscal crisis and its aftermath.
Family reunification was producing a wider variety of immigrants, fewer of whom were as highly educated as their predecessors, but the changed economic conditions in New York also limited opportunities for professional jobs even among highly qualified immigrants.
Over the next two decades many Indians would turn to jobs in manufacturing, sales, and small business.

The process of economic diversification within New York's Indian population began with professional immigrants who switched careers and opened ethnic businesses.
In the late 1960s and early 1970s, ex-professionals opened a few Indian-owned groceries, electronics and appliance shops, and insurance agencies in Queens.
In doing so they pioneered a new area of nonprofessional work in which later Indian immigrants would follow.
Soon a core of ethnic Indian businesses was joined by traditional merchants from India and its overseas communities, and by immigrants who found their first employment in these Indian businesses and would eventually open businesses of their own.

One day in 1970 G. L. Soni, a civil engineer living in Elmhurst, spotted a business location for sale in his neighborhood.
He consulted with his brother about the need for an Indian grocery store in Queens, and on the auspicious day of Vijaya Dashami, or Dussehra, the Indian festival, opened House of Spices on Broadway in Elmhurst.
Sitting in his office at the back of his store, Soni reminisced, "The Indian population was multiplying in Queens and yet there were no Indian stores.
This business location was great because it was near the junction of E/F and 7 subways, and many apartments where new immigrants lived.
Sam & Raj opened here in 1973 before they moved to their present location on 74th Street, and we started another store in Flushing, the other large area of Indian concentration.
I did not know anything about business and had to start from scratch.
At that time, we were all professionals who turned businessmen."

Over the next twenty-five years Soni expanded his store into a chain of retail grocery businesses, and later into one of the largest Indian wholesale grocery business in North America, distributing his House of Spices and Laxmi brand items to grocery stores in every town with an Indian population.
In response to increasing Indian retail competition, Soni moved completely out of the retail business.
"I have survived and expanded only because of constantly changing and repositioning.
Otherwise, at this time when the conditions have completely altered, most of the pioneer businessmen are facing difficult time."

\text{A. Sahani} came to the United States in 1971 as a mechanical engineer but soon, as an agent of an American insurance company, started his own insurance firm, serving the growing Indian population in New York.
First his younger brother, and later his own wife, who joined him in New York after their marriage in India in 1978, helped in his expanding business.
Sahani's clients were primarily North Indians engaged in particular business lines and from certain castes.
Over the years Sahani maintained social ties with his clients and became a part of their social networks; he and his family regularly attended many social events and other community activities.
He had survived the competition from new Indian insurance agents by maintaining his base of long-settled Indian immigrant families.

Two Indian engineer friends decided to make a career move in 1973 by opening an electronics and appliance store, which they called Sam & Raj.
They remained at their Broadway location in Elmhurst until 1976, when their lease expired and then moved to a nearby place on 74th Street in Jackson Heights.
Subhash Kapadia ("Sam") remained in this business for twenty-five years, keeping the name Sam & Raj original partner left.
In the 1970s Sam & Raj became a household name for the middle-class Indian customers of its electronic goods and appliances, stocked both for local voltage and for use in India.
Not only Queens residents but Indians visiting New York from other states or from India soon became familiar with 74th Street and Sam & Raj.
Kapadia became active both in his Gujarati community and in the Jackson Heights Merchants Association.
HE noted, however, that his local patronage declined in the late 1980s and the 1990s.
"Many more Indian stores have opened in this area, and it is difficult to compete for every cent.
At the same time, the purchase power of Indian customers has gone down.
Now a major portion of our business comes from mail orders rather than retail sales to visiting customers."

The Indian professionals-turned-businessmen differed from the professionals of the 1960s and 1970s, who maintained upper-class Indian networks in either Manhattan or the suburbs.
Queens-based businessmen were active in almost every new regional and religious community organization in the borough, and often served as leaders in cultural activities.
Still, some of these businessmen also maintained their alliances with Indian professionals, and together formed an elite layer of pan-Indian community leadership consisting of highly educated upper-class Indians.
As the Indian immigrant population expanded to include lower-middle-class and poorer Indian immigrants, the gap between elite leaders and ordinary residents in Queens also widened.

** New Occupations
** Ethnic Niches
** Organizing Class Interests

* Counseling Introduction Text

Asian-Indian individuals and families who immigrate to the United States often find themselves caught between differing values and cultural patterns of their home country and their adopted country.
While this experience itself is painful at various levels of life, it becomes all the more painful when a family experiences this difference between two or more generations living under the same roof.
Therefore, the purpose of this book is to offer a pastoral psychotherapeutic model for intervention with Asian-Indian individuals and families caught between two conflicting cultures, namely the Indian and American/Western cultures.
It is an undertaking that calls for a liberative pastoral care praxis.
