#+TITLE: Reading Journal 2
#+AUTHOR: Eric Nguyen

* 3 The Early Years

"Is my skin brown because I drink chocolate milk?"

- A large audience asked about race-related memories:

  + Only invoked negative emotion

  + Many people haven't talked about such memories with others

    - Does this confusion lead into adulthood?

** Preschool Conversations

- 1st conversation:
  + Friend: You're "black"
  + Tatum: No I'm "tan"

  + Perhaps younger self had internalized racist messages?
    (e.g., lighter skin = better)

- Children indeed notice physical differences:
  + Skin color
  + Hair texture
  + Shape of one's facial features

  + What do you tell them when they ask?

- White mom helping out brown-skin daughter:
  + Tatum's youngest son, David, asks: "Why don't they match?"
  + Tatum: "They don't have to match. Sometimes they do, sometimes they don't"

- David (3 y.o.) overgeneralized seeing White parents with White children and Black parents with Black children

- Tatum's oldest son, Jonathan, tells his mother
  "Eddie says my skin is brown because I drink too much chocolate milk. Is that true?"
  + Tatum: "No, your skin is brown because you have something in your skin called melanin. It helps protect from the sun."
  + Tatum reinforces a positive image of having black skin in her son

- Eddie was a White (3 y.o.) who observed a physical difference and was now searching for an explanation

- While Tatum had been helping her son's better understand race, she was concerned about whether anyone had set Eddie straight

  + So, she asks the teachers how they were handling children's questions about racial differences, and they say "It really hasn't come up."

  + Yet, Jonathan had reported such conversations?

- Imagine scenario:
  + White mother w/ white daughter
  + They pass by Black woman and child
  + White daughter: "Why that girl so dirty?"
    - Bad response: "ssh!"
    - Good response: "She isn't dirty. It's just a different color"

    - The bad response makes talking about race become taboo

** Blackness, Whiteness, and Painful History

- Preschool children are quite literal in their use of language and concrete in their thinking
  + They may be confused by the symbolic constructs that adults use

- Grocery shopping with Jonathan:
  + Jonathan: "Am I black?"
  + Tatum: "Yes"
  + Jonathan: "But I'm brown"
  + Tatum: "Black is the term used to represent African Americans"
  + Jonathan: "All whites are the same white"
  + Tatum: "No they aren't and heres proof"
  + Jonathan: "I concede my point"

- Symbols of adult language:
  + "Yellow" => Asian
  + "Red" => Native American
  + "Black" => African American

- Why are Africans in America?
  + Time to talk slavery
    - Europeans needed people to develop America
    - Africans were strong and smart
    - Get Africans (by kidnapping since they didn't want to pay)
  + Three points of consideration
    1. Don't frighten the 14 y.o. into worrying
    2. African ancestors weren't passive victims, but resisted
    3. Not all White people were bad; you can have White friends

- Why didn't they go back to Africa?
  + Some did, but others
    - had no money
    - had family here

- Good thing to introduce your kids to slavery, putting emphasis on positive aspects and avoiding internalizing messages

- Rebellions and resistance by enslaved Africans is rarely discussed
  + White teachers are unconfortable with this and other examples of the painful history of race relations in the US
  + It's hard for teachers to tell small children about slavery
    - Black young men were lynched
    - Killing Black children at their prayers

- While it's necessary to be honest about racism of the past and the present, it's more important to empower children with the vision that change is possible
  + Concrete examples are critical

- It's necessary to show that White people can be bad (slaveowners) and good (abolitionists)

** A Question of Color

- /Race constancy/: one's racial group membership is fixed and will not change.
  + Children don't grasp this concept until they are 6-7 y.o.

- "Do I have to be black to be a chief of paramedics"

- Societal preference for light skin and relative advantage historically bestowed on light-skinned Blacks, often referred to as colorism, manifests itself not only in the marketplace but even within Black families

- Skin-color prejudice found within Black communities is toxic to children and adults

- We need to examine not only our behavior toward our children, but also the language we use around them.

  + Is /black/ ever used as a derogatory term to describe others, as in "that black so-and-so?"

- Perceived "good" hair: straight hair

** "It's That Stuff Again": Developing a Critical Consciousness

- "Hey it's that stuff again" (referring to gender bias with respect to racial bias. examples being racist, sexist, classist)

- Important for children to recognize other forms of oppression

- Point out omission or distortions that you notice

- Children can learn to question whether demeaning or derogatory depictions of other people are stereotypes

- Children recognized for their protest of misrepresentation of history

* 4 Identity Development in Adolescnce

- Why are all the Black kids sitting together in the cafeteria?

- Racial grouping begins by 6th or 7th grade.

  + Why? Puberty

    - "Who am I?" ("Who am I ethnically and/or racially?", "What does it mean to be Black?")

    - "Who can I be?"

- While all adolescents start looking at themselves in new ways, not all adolescents think about themselves in racial terms.

- Search for personal identity can involve several dimensions of an adolescent's life:

  + vocational plans

  + religious beliefs

  + values and preferences

- James Marcia described four identity "statuses" to characterize the variation in the identity search process:

  1) diffuse - little exploration or active consideration of a particular domain, and no psychological commitment

  2) foreclosed - commitment to particular roles or beliefs systems, often those selected by parents, without actively considering alternatives

  3) moratorium - active exploration of roles and beliefs in which no commitment has yet been made

  4) achieved - strong personal commitment to a particular dimension of identity following a period of high exploration

- It is not unusual for an adolescent to be actively exploring one dimension while another remains relatively unexamined

  + Not surprising that researchers have found that adolescents of color are more likely to be actively engaged in an exploration of their racial or ethnic identity than are White adolescents

- Why do Black youths, in particular, think about themselves in terms of race?
  Because that is how the rest of the world thinks of them.

- If you ask Tatum's son, David, how he would describe himself:
  + likes computer games
  + has an older brother
  + Probably not mention that he's black

** Understanding Racial Identity Development

- Five stages of racial identity development
  1. Pre-encounter
  2. Encounter
  3. Immersion/emersion
  4. Internationalization
  5. Internationalization-commitment

- Pre-encounter stage:
  + The Black child absorbs many of the beliefs and values of the dominant White culture, including the idea that it's better to be White
  + The personal and social significance of one's racial group membership has not yet been realized, and racial identity is not yet under examination
  + Transitions to encounter stage when environmental cues change and the world begins to reflect Blackness back

- Encounter stage:
  + Acknowledge the personal impact of racism
  + Begins to understand the significance of race
  + Transitions to immersion/emersion stage as early as junior high school

- Immersion/emersion stage:
  + 1/3 of 48 participants had thought about the effects of ethnicity on their future, had discussed the issues with family and friends, and were attempting to learn more about their group

- Internationalization stage:
  + There usually is a recognizable racial pattern to how children are assigned to groups in class
  + In racially mixed schools, Black children are much more likely to be in the lower track than in the honors track

- Internationalization-commitment stage:
  + Birthday party effect: Young children's birthday parties in multiracial communities are often a reflection of the community's diversity
    - At puberty, when parties become sleepovers or boy-girl events, they become less racially
  + Issues of emerging sexuality and the societal messages about who is sexually desirable leave young Black women in a very devalued position

- Young Black men are often seen in media having involved in violent crimes, leading to suspicion and fear of them

  + However, the culture has embraced the black athlete

- Malcom X wanted to be a lawyer:
  + His teacher: "That's no realistic goal for a nxxxxr; do carpentry instead"

- Teachers would say the n-word anymore, but they still suggest black people to go to a community college

- Example:
  + young Black woman attending desegregated school
  + encouraged by teacher to attend upcoming school dance
  + she ain't going
  + "Oh come on, I know you people love to dance."
  + next day
  + bumps into White girl
  + tells White girl story
  + "Oh, Mr. Smith is such a nice guy, I'm sure he didn't mean it like that. Don't be so sensitive."
  + bruh what. gtfo

** Coping with Encounters: Developing an Oppositional Identity

- White peers are unprepared to respond in supportive ways

- Signithia Fordham and John Ogbu
  + Blacks upset in growing awareness of systematic exclusion of Black people
  + Some stuff not appropriate for blacks
  + Some stuff more appropriate for them

- Authentically Black stuff highly valued
  + Blacks gotta listen to rap, otherwise u not cool

- In racially mixed settings, racial grouping is a developmental process in response to an environmental stressor, racism.

- Young people are operating with a very limited definition of what it means to be Black, based largely on cultural stereotypes

** Oppositional Identity Development and Academic Achievement

- For Blacks, smart => less cool
  + "Not really Black"
  + Peer rejection

- Academically successful Black students also need a strategy to find acceptance among their White classmates

  + Racelessness - individuals assimilate into the dominant group by de-emphasizing characteristics that might identify them as members of the subordinate group

- Black students can play down Black identity in order to succeed in school and mainstream institutions without rejecting his Black identity and culture

- Instead of raceless, Black students can become emissary, seeing their achievements as advancing the cause of the racial group

- Questions for educators and concerned adults:
  + How did academic achievement become defined as exclusively White behavior?
  + What is it about the curriculum and the wider culture that reinforces the notion that academic excellence is an exclusively White domain?
  + What curricular interventions might we use to encourage the development of an empowered emissary identity?

- Academic achievement did not have to mean separation from one's Black peers in segregated schools

** The Search for Alternative Images

- Young people should be exposed to African American academic achievement in their early years

- Many Black students never get to college

  + Never understand what it means to be Black; this knowledge could've helped them stayed in school

    - Young people are developmentally ready for this information in adolescence.
      We ought to provide it.

** Not at the Table

- Some Black students may not be developmentally ready for the Black table in junior or senior high school

- "Authentic Blackness" excludes Black people who don't "fit in"

- It is immensely helpful to be able share one's experiences with others who have lived it

- Even when White friends are willing to listen and bear witness to one's stuggles, they cannot really share the experience.

- When one is faced with what Chester Pierce calls the "mundane extreme environmental stress" of racism, in adolescence or in adulthood, the ability to see oneself as part of a larger group from which one can draw support is an important coping strategy

  + Those who don't experience a shared identity to some subset of their racial group are at risk for considerable social isolation

** An Alternative to the Cafeteria Table

- Developmental need to explore the meaning of one's identity with others who are engaged in a similar process manifests itself informally in school corridors and cafeterias across

- Improve academic achievement through Student Efficacy Training (SET)

  + Students meet with staff members and discuss academic issues such as

    - Racial encounters

    - Feelings of isolation

    - Test anxiety

    - Homework dilemmas

* 6 The Development of White Identity

- "I'm not ethnic, I'm just normal"

  + Whiteness the norm?

  + "No one taught us about race"

- Counseling psychologist Janet Helms:

  + Task of people of color is to resist negative societal messages and develop and empowered sense of self in the face of a racist society

  + Task of Whites is to develop a positive White identity based in reality, not on assumed superiority

- How can White people achieve a healthy sense of White Identity?

  + Two major developmental tasks in this process

    1. The abandonment of individual racism

    2. The recognition of and opposition to institutional and cultural racism

  + Six stages:

    1. Contact

    2. Disintegration

    3. Reintegration

    4. Pseudo-independent

    5. Immersion/emersion

    6. Autonomy

** Abandoning Racism

- Contact stage:
  + "I'm just normal"
  + No conscious consideration of their White privilege
  + Internalized many of the prevailing societal stereotypes of people of color, unaware of this socialization process
  + Think of racism as prejudiced behaviors of individuals rather than as an institutionalized system of advantage
  + Racial identity based on passive absorption of subtly communicated messages

- Disintegration stage:
  + Growing awareness of racism and White privilege as a result of personal encounters in which the social significance of race is made visible
  + Start noticing racism in everyday language of family and friends
  + New awareness creates discomfort
  + Begin seeing impact of racism in society
  + Notice societal inequities contradict American meritocracy
  + Like new converts, they can be quite zealous in their efforts
    - Point out stereotypes with friends and family

- Reintegration stage:
  + Previous feelings of guilt or denial may be transformed into fear and anger directed toward people of color
  + "If there is a problem with racism, then you people of color must have done something to cause it. And if you would just change your behavior, the problem would go away."
    - Relieves the White person of all responsibility for social change
  + Not inevitable stage, but most White people who speak up against racism will attest to the temptation they sometimes feel to slip back into collusion and silence

** "But I'm an Individual!"

- Whites perceived as individuals

- The view of oneself as an individual is very compatible with the dominant ideology of rugged individualism and the American myth of meritocracy

- White Jewish students often struggle with tension between being targeted and receiving privilege

- Many White people experience powerlessness, even with privilege

- Fact is we all have a sphere of influence, some domain in which we exercise some level of power and control

** Defining a Positive White Identity

- As a White person's understanding of the complexity of institutional racism in our society deepens, the less likely he or she is to resort to explanations that blame the victim

- If a White person reaches out to a Black person and is rebuffed, it may cause the White person to retreat into "blame the victim" thinking

  + Even if these efforts to build interracial relationships are successful, the White individual must eventually confront the reality of his or her own Whiteness

- We all must be able to embrace who we are in terms of our racial and cultural heritage, not in terms of assumed superiority or inferiority, but as an integral part of our daily experience in which we can take pride

- Recognizing the need to find a more positive self-definition is a hallmark of the next phase of White racial identity development, the immersion/emersion stage

- Student Bob sees need to understand White identity

  + Bob needs other Whites who are further long in the process and can help show him the way

- White people must seek new ways of thinking about Whiteness, ways that take them beyond the role of victimizer

** The Search for White Allies and the Restoration of Hope

- There is a history of White protest against racism ("White allies")

- Not many well-known White activists against racism

- Those who oppose racism are often marginalized, and as a result, their stories are not readily accessed

- Try to address lack of knowledge of White role models

- "We need to talk about what living in this borderland feels likes, how we get there, what sustains us, and how we benefit from it.
  For me, this place of existence is tremendously exciting, invigorating, and life-affirming."

  + Though it can also be "complicated and lonely," it is also liberating, opening doors to new communities, creating possibilities for more authentic connections with people of color, and in the process, strengthening the coalitions necessary for genuine social change

* 7 White Identity and Affirmative Action

- "I'm in favor of affirmative action except when it comes to my jobs."

- The presence of an affirmative action policy can be enough to draw an individual's attention to his own Whiteness.

  + What will affirmative action mean in my life?

  + Will I get the job I want, or will it go to some "minority"?

  + Will the opportunities I expected still be there for me, or will I be the victim of "reverse racism"?

- Even those Whites who have not given much though to their racial identity have thought about affirmative action

- Affirmative action is designed to represent whiteness as a disadvantage

- White disadvantage takes the form of questions about affirmative action and "reverse discrimination"

** What Is Affirmative Action?
** Aversive Racism and Affirmative Action
** "Not a Prejudiced Bone in Their Bodies": A Case Example
** Keeping Our Eyes on the Prize: Goal-Oriented Affirmative Action
** White Disadvantage Revisited
